name: Build

on:
  push:
    branches: ["**"]

jobs:
  web:
    name: Export (Web)
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.3.0

    steps:
      - uses: actions/checkout@v4

      - name: Move export templates into place
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.3.stable \
             ~/.local/share/godot/export_templates/4.3.stable

      - name: Export
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: idleplane-web
          path: build/web/
          retention-days: 14
